/*
    EVE Target Intel - Configuration Constants
    
    Copyright (C) 2025 moregh (https://github.com/moregh/)
    Licensed under AGPL License.
*/

export const CACHE_EXPIRY_HOURS = 12;
export const LONG_CACHE_EXPIRY_HOURS = 168;
export const ZKILL_KILLS_CACHE_HOURS = 3;
export const ESI_KILLMAILS_CACHE_HOURS = 168;
export const MAX_ESI_CALL_SIZE = 100;
export const MAX_CONCURRENT_IMAGES = 4;
export const CHUNK_SIZE = 50;
export const CHUNK_DELAY = 25;
export const STATS_UPDATE_DELAY = 100;
export const DB_NAME = 'EVETargetIntelDB';
export const DB_VERSION = 3;
export const VERSION = "0.10.4";

export const PROGRESS_UPDATE_THROTTLE_MS = 50;
export const TIMER_UPDATE_INTERVAL_MS = 100;
export const TIMER_UPDATE_THROTTLE_MS = 100;
export const LOADING_DISPLAY_DELAY_MS = 300;
export const LOADING_HIDE_DELAY_MS = 500;
export const CHARACTER_COUNT_DEBOUNCE_MS = 150;
export const SCROLL_STATE_TIMEOUT_MS = 150;
export const SCROLL_THROTTLE_MS = 8;
export const ANIMATION_FRAME_THROTTLE_FPS = 16;
export const POPUP_SHOW_DELAY = 400;

export const MIN_CHARACTER_NAME_LENGTH = 3;
export const MAX_CHARACTER_NAME_LENGTH = 37;
export const MAX_SINGLE_NAME_LENGTH = 24;
export const MAX_FAMILY_NAME_LENGTH = 12;
export const MAX_FIRST_MIDDLE_NAME_LENGTH = 24;

export const GRID_VIEW_ITEM_HEIGHT_PX = 150;
export const MIN_GRID_ITEM_WIDTH_PX = 270;
export const USER_NOTIFICATION_DISPLAY_MS = 1500;

export const CHARACTER_PORTRAIT_SIZE_PX = 64;
export const CORP_LOGO_SIZE_PX = 32;
export const ALLIANCE_LOGO_SIZE_PX = 32;

export const PERFORMANCE_CONFIG = {
    VIRTUAL_SCROLL_BUFFER: 10,
    ANIMATION_FRAME_THROTTLE: 8,
    OBSERVER_THROTTLE: 50,
    MAX_ELEMENT_POOL_SIZE: 50,
    BATCH_SIZE: 20,
    IMAGE_INTERSECTION_MARGIN: '50px',
    ANIMATION_INTERSECTION_MARGIN: '20px'
};

export const ESI_BASE = "https://esi.evetech.net/latest";
export const USER_AGENT = `EVETargetIntel/${VERSION} (+https://github.com/moregh/moregh.github.io/)`;
export const ALLOWED_IMAGE_URLS = ['images.evetech.net', 'imageserver.eveonline.com'];
export const ESI_HEADERS = {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'User-Agent': USER_AGENT,
    'X-User-Agent': `${USER_AGENT}`
};

export const ZKILL_CARD_ANIMATION_DURATION_MS = 300;
export const ZKILL_CARD_BACKDROP_BLUR = '12px';
export const ZKILL_DATA_CACHE_DURATION_MS = 180 * 60 * 1000;
export const MAX_KILLMAILS_TO_FETCH = 1000;
export const KILLMAIL_BATCH_SIZE = 10;
export const KILLMAIL_FETCH_DELAY_MS = 10;

export const ZKILL_PAGINATION_CONFIG = {
    MIN_KILLMAILS: 100,
    TARGET_DAYS: 30,
    MAX_PAGES: 5,
    PAGE_FETCH_DELAY_MS: 100,
    VERIFY_AFTER_PAGES: 5
};

export const ZKILL_CONFIG = {
    PROXY_BASE_URL: 'https://zkill2.zkillproxy.workers.dev/',
    POW_DIFFICULTY: 12,
    REQUEST_INTERVAL_MS: 500,
    CACHE_DURATION_MS: ZKILL_DATA_CACHE_DURATION_MS,
    REQUEST_TIMEOUT_MS: 15000,
    MAX_RETRIES: 3,
    MAX_CONCURRENT_REQUESTS: 1,
    BATCH_DELAY_MS: 500
};

export const VIRTUAL_SCROLL_CONFIG = {
    CONTAINER_HEIGHT: '75vh',
    MIN_HEIGHT: '720px',
    MAX_HEIGHT: '900px',
    BUFFER_SIZE: 5,
    GRID_GAP: '1.35rem',
    CONTENT_PADDING: '1.8rem',
    MIN_ITEM_WIDTH: 252,
    CONTAINER_MIN_WIDTH: 270,
    CONTAINER_PADDING: 60,
    SCROLL_DEBOUNCE_MS: 8,
    MAX_RENDERED_ELEMENTS: 200,
    MIN_INITIAL_ROWS: 6
};

export const VIEW_DIMENSIONS = {
    list: { height: 90, itemsPerRow: 1 },
    grid: { height: 150, itemsPerRow: null }
};

export const INPUT_SECTION_HOVER_DELAY_MS = 200;

export const FILTER_MIN_ENTITY_NAME_LENGTH = 3;
export const FILTER_MAX_ENTITY_NAME_LENGTH = 50;
export const FILTER_DEFAULT_MIN_CORP_SIZE = 1;
export const FILTER_DEFAULT_MAX_CORP_SIZE = 500;
export const FILTER_DEFAULT_MIN_ALLIANCE_SIZE = 1;
export const FILTER_DEFAULT_MAX_ALLIANCE_SIZE = 10000;
export const FILTER_NAME_DEBOUNCE_MS = 300;
export const FILTER_CACHE_SIZE_LIMIT = 20;

export const IMAGE_OBSERVER_THRESHOLD = 0.2;
export const IMAGE_OBSERVER_ROOT_MARGIN = '20px';
export const IMAGE_OPACITY_LOADING = 0.3;
export const IMAGE_OPACITY_ERROR = 0.5;
export const IMAGE_OPACITY_LOADED = 1;

export const CLEANUP_ELEMENT_BATCH_SIZE = 20;
export const TOP_ITEMS_DISPLAY_LIMIT = 3;
export const BREAKDOWN_DISPLAY_LIMIT = 4;

export const CHART_WIDTH_PX = 320;
export const CHART_HEIGHT_PX = 180;
export const CHART_MARGIN_TOP_PX = 20;
export const CHART_MARGIN_RIGHT_PX = 10;
export const CHART_MARGIN_BOTTOM_PX = 40;
export const CHART_MARGIN_LEFT_PX = 50;
export const CHART_BAR_SPACING_PX = 2;
export const CHART_STEPS = 4;
export const CHART_LABEL_INTERVAL_DIVISOR = 8;
export const CHART_COLOR_THRESHOLD_HIGH = 0.7;
export const CHART_COLOR_THRESHOLD_MEDIUM = 0.4;

export const ENTITY_MIN_WIDTH_PX = 252;
export const ENTITY_CARD_MIN_WIDTH_PX = 300;
export const CONTAINER_PADDING_PX = 60;
export const ENTITY_LOGO_SIZE_PX = 64;
export const IMAGE_PLACEHOLDER_SIZE_PX = 32;

export const ZKILL_TIMER_UPDATE_INTERVAL_MS = 100;
export const ZKILL_PROGRESS_CONNECTING = 10;
export const ZKILL_PROGRESS_ESI_BASE = 60;
export const ZKILL_PROGRESS_AFFILIATIONS = 75;
export const ZKILL_PROGRESS_PROCESSING = 90;
export const ZKILL_RECENT_KILLS_LIMIT = 5;
export const ZKILL_NAVIGATION_CLOSE_DELAY_MS = 350;
export const ZKILL_NAVIGATION_HISTORY_LIMIT = 3;
export const ZKILL_EFFICIENCY_THRESHOLD_HIGH = 80;
export const ZKILL_EFFICIENCY_THRESHOLD_MEDIUM = 50;
export const ZKILL_GANG_RATIO_THRESHOLD_HIGH = 70;
export const ZKILL_GANG_RATIO_THRESHOLD_LOW = 30;
export const ZKILL_WORMHOLE_SECURITY = -1.0;
export const ZKILL_SECURITY_HIGH_THRESHOLD = 0.5;
export const ZKILL_SECURITY_NULL_THRESHOLD = 0.0;
export const ZKILL_SECURITY_WSPACE_THRESHOLD = -0.99;

export const SCROLL_DETECTION_TIME_MS = 150;
export const CONCURRENT_IMAGE_LOAD_DIVISOR = 2;

export const ESI_BATCH_MAX_CONCURRENCY = 8;
export const ESI_MISSING_NAMES_WARNING_TIMEOUT_MS = 1500;
export const THREAT_ASSESSMENT = {
    RECENCY: {
        KILL_AGE_WEIGHT_HALFLIFE_HOURS: 168,
        RECENT_KILL_MULTIPLIER: 3.0,
        VERY_RECENT_THRESHOLD_MINUTES: 20,
        VERY_RECENT_MULTIPLIER: 5.0,
    },

    FREQUENCY: {
        HIGH_FREQUENCY_KILLS_PER_DAY: 10,
        MODERATE_FREQUENCY_KILLS_PER_DAY: 3,
        LOW_FREQUENCY_KILLS_PER_DAY: 1,
        FREQUENCY_WINDOW_DAYS: 7,
    },

    HVT: {
        VALUE_THRESHOLD_HIGH: 1000000000,
        VALUE_THRESHOLD_VERY_HIGH: 10000000000,
        VALUE_THRESHOLD_EXTREME: 100000000000,
        MIN_KILLS_FOR_DETECTION: 5,
        MIN_FREQUENCY_PERCENT: 8,
        MIN_FREQUENCY_PERCENT_STRICT: 15,
        CONFIDENCE_THRESHOLD_VERY_HIGH: 150,
        CONFIDENCE_THRESHOLD_HIGH: 100,
        CONFIDENCE_THRESHOLD_MEDIUM: 50,
        CONFIDENCE_THRESHOLD_LOW: 20,
    },

    BLOPS: {
        MIN_KILLS_FOR_DETECTION: 5,
        MIN_KILLS_FOR_HIGH_CONFIDENCE: 8,
        MIN_FREQUENCY_PERCENT: 8,
        MIN_FREQUENCY_PERCENT_STRICT: 15,
        SHIP_IDS: [22456, 22464, 22466, 22460, 28844, 42125, 42246],
        GROUP_ID: 898,
        CONFIDENCE_THRESHOLD_VERY_HIGH: 150,
        CONFIDENCE_THRESHOLD_HIGH: 100,
        CONFIDENCE_THRESHOLD_MEDIUM: 50,
        CONFIDENCE_THRESHOLD_LOW: 20,
    },

    CYNO: {
        MIN_KILLS_FOR_DETECTION: 3,
        MIN_FREQUENCY_PERCENT: 10,
        SHIP_IDS: [33328, 11963, 11969, 11965, 11961],
        FORCE_RECON_GROUP_ID: 833,
        CONFIDENCE_THRESHOLD_VERY_HIGH: 150,
        CONFIDENCE_THRESHOLD_HIGH: 100,
        CONFIDENCE_THRESHOLD_MEDIUM: 50,
        CONFIDENCE_THRESHOLD_LOW: 20,
    },

    FLEET: {
        SOLO_MAX: 1,
        SMALL_GANG_MAX: 10,
        MEDIUM_FLEET_MAX: 25,
        LARGE_FLEET_MAX: 40,
        BLOB_THRESHOLD: 30,
    },

    ACTIVITY: {
        KILLS_LAST_7D_VERY_HIGH: 15,
        KILLS_LAST_7D_HIGH: 10,
        KILLS_LAST_7D_MODERATE: 5,
        KILLS_LAST_7D_LOW: 3,
        KILLS_LAST_30D_INACTIVE_THRESHOLD: 8,
        ACTIVE_DAYS_VERY_HIGH: 20,
        ACTIVE_DAYS_HIGH: 15,
        ACTIVE_DAYS_MODERATE: 10,
        ACTIVE_DAYS_LOW: 5,
        SYSTEM_DIVERSITY_VERY_HIGH: 15,
        SYSTEM_DIVERSITY_HIGH: 10,
        SYSTEM_DIVERSITY_MODERATE: 5,
        FLEET_FIGHT_SPIKE_MIN_KILLS: 15,
        FLEET_FIGHT_SPIKE_THRESHOLD: 40,
    },

    RISK_WEIGHTS: {
        RECENCY: 0.25,
        FREQUENCY: 0.30,
        HVT_HUNTING: 0.10,
        SHIP_CAPABILITY: 0.10,
        SECURITY_PREFERENCE: 0.10,
        SOLO_RATIO: 0.20,
    },

    RISK_SCORE: {
        SPACE_WEIGHT_HIGHSEC: 0.4,
        SPACE_WEIGHT_LOWSEC: 0.45,
        SPACE_WEIGHT_NULLSEC: 0.45,
        SPACE_WEIGHT_WSPACE: 0.5,
        HVT_BONUS_VERY_HIGH: 15,
        HVT_BONUS_HIGH: 12,
        HVT_BONUS_DEFAULT: 8,
        CAPITAL_HUNTER_BONUS: 10,
        AVG_VALUE_HIGH_THRESHOLD: 1000000000,
        AVG_VALUE_HIGH_BONUS: 12,
        AVG_VALUE_MEDIUM_THRESHOLD: 500000000,
        AVG_VALUE_MEDIUM_BONUS: 6,
        AVG_VALUE_LOW_THRESHOLD: 250000000,
        AVG_VALUE_LOW_BONUS: 3,
        SOLO_HIGH_RATIO: 0.5,
        SOLO_HIGH_BONUS: 15,
        SOLO_MEDIUM_RATIO: 0.2,
        SOLO_MEDIUM_BONUS: 10,
        ROAMING_BONUS: 8,
        SHIP_DIVERSITY_HIGH: 20,
        SHIP_DIVERSITY_HIGH_BONUS: 3,
        SHIP_DIVERSITY_MEDIUM: 15,
        SHIP_DIVERSITY_MEDIUM_BONUS: 1,
        CYNO_BONUS_VERY_HIGH: 20,
        CYNO_BONUS_HIGH: 15,
        CYNO_BONUS_DEFAULT: 10,
        BLOPS_BONUS_VERY_HIGH: 18,
        BLOPS_BONUS_HIGH: 14,
        BLOPS_BONUS_DEFAULT: 10,
        SOLO_RATIO_HIGH_BONUS: 20,
        SOLO_RATIO_MEDIUM_BONUS: 15,
        ACTIVITY_KILLS_7D_VERY_HIGH: 15,
        ACTIVITY_KILLS_7D_VERY_HIGH_BONUS: 28,
        ACTIVITY_KILLS_7D_HIGH: 10,
        ACTIVITY_KILLS_7D_HIGH_BONUS: 25,
        ACTIVITY_KILLS_7D_MODERATE: 5,
        ACTIVITY_KILLS_7D_MODERATE_BONUS: 20,
        ACTIVITY_KILLS_7D_LOW: 3,
        ACTIVITY_KILLS_7D_LOW_BONUS: 15,
        ACTIVITY_KILLS_7D_MINIMAL: 1,
        ACTIVITY_KILLS_7D_MINIMAL_BONUS: 10,
        ACTIVITY_DAYS_VERY_HIGH: 20,
        ACTIVITY_DAYS_VERY_HIGH_BONUS: 30,
        ACTIVITY_DAYS_HIGH: 15,
        ACTIVITY_DAYS_HIGH_BONUS: 25,
        ACTIVITY_DAYS_MODERATE: 10,
        ACTIVITY_DAYS_MODERATE_BONUS: 20,
        ACTIVITY_DAYS_LOW: 7,
        ACTIVITY_DAYS_LOW_BONUS: 15,
        ACTIVITY_DAYS_MINIMAL: 5,
        ACTIVITY_DAYS_MINIMAL_BONUS: 10,
        ACTIVITY_DAYS_VERY_LOW: 3,
        ACTIVITY_DAYS_VERY_LOW_BONUS: 6,
        SYSTEM_DIVERSITY_VERY_HIGH: 15,
        SYSTEM_DIVERSITY_VERY_HIGH_BONUS: 12,
        SYSTEM_DIVERSITY_HIGH: 10,
        SYSTEM_DIVERSITY_HIGH_BONUS: 8,
        SYSTEM_DIVERSITY_MODERATE: 5,
        SYSTEM_DIVERSITY_MODERATE_BONUS: 4,
        FLEET_VARIANCE_HIGH: 50,
        FLEET_VARIANCE_HIGH_BONUS: 8,
        FLEET_VARIANCE_MEDIUM: 20,
        FLEET_VARIANCE_MEDIUM_BONUS: 4,
        RECENCY_RATIO_LOW_1: 0.08,
        RECENCY_RATIO_PENALTY_1: 0.35,
        RECENCY_RATIO_LOW_2: 0.15,
        RECENCY_RATIO_PENALTY_2: 0.55,
        RECENCY_RATIO_LOW_3: 0.25,
        RECENCY_RATIO_PENALTY_3: 0.7,
        INACTIVE_TOTAL_HIGH: 150,
        INACTIVE_30D_LOW: 8,
        INACTIVE_PENALTY_1: 0.4,
        INACTIVE_TOTAL_MEDIUM: 80,
        INACTIVE_30D_MEDIUM: 5,
        INACTIVE_PENALTY_2: 0.5,
        ACTIVITY_MAX_SCORE: 60,
        EXTREME_THRESHOLD: 110,
        VERY_HIGH_THRESHOLD: 90,
        HIGH_THRESHOLD: 70,
        MODERATE_THRESHOLD: 50,
        LOW_THRESHOLD: 20,
        FLEET_SPIKE_MIN_KILLS_DAY: 15,
        FLEET_SPIKE_MAJOR_THRESHOLD: 40,
        FLEET_SPIKE_MAJOR_MULTIPLIER: 4,
        FLEET_SPIKE_MAJOR_MAX_DAYS: 2,
        FLEET_SPIKE_MEDIUM_THRESHOLD: 25,
        FLEET_SPIKE_MEDIUM_MULTIPLIER: 5,
        FLEET_SPIKE_MEDIUM_MAX_DAYS: 1,
        FLEET_SPIKE_DAY_RATIO: 0.6,
        FLEET_SPIKE_MIN_TOTAL: 20,
        FLEET_SPIKE_MAX_SYSTEMS: 2,
        FLEET_SPIKE_MIN_AVG_FLEET: 20,
        FLEET_SPIKE_BONUS: 8,
        MONTHLY_KILLS_VERY_HIGH: 20,
        MONTHLY_KILLS_VERY_HIGH_BONUS: 15,
        MONTHLY_KILLS_HIGH: 10,
        MONTHLY_KILLS_HIGH_BONUS: 10,
        MONTHLY_KILLS_MODERATE: 5,
        MONTHLY_KILLS_MODERATE_BONUS: 8,
        MONTHLY_KILLS_LOW: 2,
        MONTHLY_KILLS_LOW_BONUS: 5,
        ACTIVE_MONTHS_VERY_HIGH: 5,
        ACTIVE_MONTHS_VERY_HIGH_BONUS: 10,
        ACTIVE_MONTHS_HIGH: 3,
        ACTIVE_MONTHS_HIGH_BONUS: 8,
        ACTIVE_MONTHS_LOW: 1,
        ACTIVE_MONTHS_LOW_PENALTY: 0.7,
        MONTHLY_CONSISTENCY_MIN: 0.8,
        MONTHLY_CONSISTENCY_MAX: 1.3,
        MONTHLY_CONSISTENCY_BONUS: 8,
        MONTHLY_ACTIVITY_MAX_SCORE: 30,
    },

    TAGS: {
        ACTIVE_NOW_MINUTES: 20,
        ACTIVE_RECENTLY_HOURS: 2,
        HVT_HUNTER_MIN_SCORE: 60,
        BLOPS_USER_MIN_SCORE: 60,
        CYNO_PILOT_MIN_SCORE: 60,
        CAPITAL_PILOT_MIN_KILLS: 3,
        SOLO_HUNTER_MIN_PERCENT: 50,
        SMALL_GANG_MIN_PERCENT: 50,
        FLEET_FIGHTER_MIN_PERCENT: 60,
        GATE_CAMPER_CONCENTRATION: 0.5,
        BLOB_MIN_AVERAGE_FLEET: 30,
        BLOB_MIN_MAX_FLEET: 50,
        BLOB_MIN_RATIO: 0.5,
    },

    SCORING: {
        RECENCY: {
            VERY_RECENT_SCORE: 100,
            TWO_HOUR_SCORE: 95,
            SIX_HOUR_SCORE: 90,
            ONE_DAY_SCORE: 80,
            THREE_DAY_SCORE: 70,
            SEVEN_DAY_SCORE: 55,
            FOURTEEN_DAY_SCORE: 35,
            THIRTY_DAY_SCORE: 20,
            OLD_SCORE: 10,
            TWO_HOUR_THRESHOLD: 2,
            SIX_HOUR_THRESHOLD: 6,
            ONE_DAY_THRESHOLD: 24,
            THREE_DAY_THRESHOLD: 3,
            SEVEN_DAY_THRESHOLD: 7,
            FOURTEEN_DAY_THRESHOLD: 14,
            THIRTY_DAY_THRESHOLD: 30,
        },

        FREQUENCY: {
            KILLS_5000_SCORE: 100,
            KILLS_2000_SCORE: 95,
            KILLS_1000_SCORE: 90,
            KILLS_500_SCORE: 80,
            KILLS_250_SCORE: 70,
            KILLS_100_SCORE: 60,
            KILLS_50_SCORE: 45,
            KILLS_25_SCORE: 30,
            KILLS_10_SCORE: 20,
            KILLS_5000_THRESHOLD: 5000,
            KILLS_2000_THRESHOLD: 2000,
            KILLS_1000_THRESHOLD: 1000,
            KILLS_500_THRESHOLD: 500,
            KILLS_250_THRESHOLD: 250,
            KILLS_100_THRESHOLD: 100,
            KILLS_50_THRESHOLD: 50,
            KILLS_25_THRESHOLD: 25,
            KILLS_10_THRESHOLD: 10,
            KILLS_PER_DAY_LOW: 2,
            KILLS_PER_DAY_HIGH: 5,
            RECENT_ACTIVITY_BONUS_LOW: 5,
            RECENT_ACTIVITY_BONUS_HIGH: 10,
            SCORE_MULTIPLIER_LOW: 2,
        },

        SECURITY: {
            WSPACE_SCORE: 95,
            POCHVEN_SCORE: 90,
            NULLSEC_SCORE: 85,
            LOWSEC_SCORE: 75,
            HIGHSEC_SCORE: 40,
            DEFAULT_SCORE: 50,
        },

        SOLO: {
            BASE_SCORE: 60,
            SOLO_60_SCORE: 95,
            SOLO_40_SCORE: 85,
            SOLO_20_SCORE: 75,
            SOLO_10_SCORE: 65,
            SOLO_60_THRESHOLD: 0.6,
            SOLO_40_THRESHOLD: 0.4,
            SOLO_20_THRESHOLD: 0.2,
            SOLO_10_THRESHOLD: 0.1,
            GANG_RATIO_THRESHOLD: 70,
            GANG_BONUS: 10,
            DANGER_RATIO_HIGH: 3,
            DANGER_RATIO_MEDIUM: 2,
            DANGER_BONUS_HIGH: 10,
            DANGER_BONUS_MEDIUM: 5,
            DEFAULT_SCORE: 50,
        },

        SHIP_CAPABILITY: {
            BLOPS_VERY_HIGH_SCORE: 60,
            BLOPS_HIGH_SCORE: 50,
            BLOPS_DEFAULT_SCORE: 35,
            CYNO_VERY_HIGH_SCORE: 70,
            CYNO_HIGH_SCORE: 55,
            CYNO_DEFAULT_SCORE: 40,
            CAPITAL_SCORE: 30,
        },

        HVT: {
            CONFIDENCE_VERY_HIGH: 1.0,
            CONFIDENCE_HIGH: 0.9,
            CONFIDENCE_MEDIUM: 0.7,
            CONFIDENCE_DEFAULT: 0.5,
            COUNT_DIVISOR: 20,
        },

        THREAT_LEVELS: {
            EXTREME_THRESHOLD: 95,
            VERY_HIGH_THRESHOLD: 85,
            HIGH_THRESHOLD: 70,
            ELEVATED_THRESHOLD: 55,
            MODERATE_THRESHOLD: 40,
            LOW_THRESHOLD: 25,
        }
    }
};
